<?xml version="1.0" ?>
<testsuite name="TestHello-20201016090716" tests="3" time="0.022" failures="0" errors="1">
	<testcase classname="TestHello" name="test_hello_hello" time="0.007"/>
	<testcase classname="TestHello" name="test_hello_name" time="0.000"/>
	<testcase classname="TestHello" name="test_base" time="0.014">
		<error type="TypeError" message="The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a int."><![CDATA[Traceback (most recent call last):
  File "test_api.py", line 12, in test_base
    rv = self.app.get('/')
  File "C:\Users\Samara\AppData\Local\Programs\Python\Python38\lib\site-packages\werkzeug\test.py", line 1006, in get
    return self.open(*args, **kw)
  File "C:\Users\Samara\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\testing.py", line 222, in open
    return Client.open(
  File "C:\Users\Samara\AppData\Local\Programs\Python\Python38\lib\site-packages\werkzeug\test.py", line 970, in open
    response = self.run_wsgi_app(environ.copy(), buffered=buffered)
  File "C:\Users\Samara\AppData\Local\Programs\Python\Python38\lib\site-packages\werkzeug\test.py", line 861, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "C:\Users\Samara\AppData\Local\Programs\Python\Python38\lib\site-packages\werkzeug\test.py", line 1096, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "C:\Users\Samara\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Samara\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Samara\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Samara\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Samara\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Samara\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Users\Samara\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "C:\Users\Samara\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2127, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a int.
]]></error>
	</testcase>
	<system-out><![CDATA[]]></system-out>
	<system-err><![CDATA[]]></system-err>
</testsuite>
